-- Fichier généré automatiquement par generateur_db.py - NE PAS ÉDITER.
-- Corrections Perso (lot 1) : libellés courts + corrections de qualité.
local DB = AscensionFR.DB.Divers

-- Correctifs qualité (évite le calque « plaques signalétiques »)
DB["All Nameplates Turned On (Combat)"]="Toutes les plaques de nom activées (combat)"
DB["Wildwood Log"]="Bûche de Wildwood"
DB["You must be in the Moonwell of the Vulture Cult Eyrie."]="Vous devez être dans le puits de lune de l'Aire du culte des vautours."

-- Libellés Ascension / UI souvent récoltés hors des grosses DB
DB["Nameplates"]="Plaques de nom"
DB["All Nameplates"]="Toutes les plaques de nom"
DB["Enemy Nameplates"]="Plaques de nom ennemies"
DB["Friendly Nameplates"]="Plaques de nom amicales"
DB["Show Nameplates"]="Afficher les plaques de nom"
DB["Hide Nameplates"]="Masquer les plaques de nom"

DB["Click to open"]="Cliquer pour ouvrir"
DB["Right-click to open"]="Clic droit pour ouvrir"
DB["Left-click"]="Clic gauche"
DB["Right-click"]="Clic droit"
DB["Shift-click"]="Maj+clic"
DB["Ctrl-click"]="Ctrl+clic"
DB["Alt-click"]="Alt+clic"

DB["Search"]="Rechercher"
DB["Filter"]="Filtrer"
DB["Refresh"]="Actualiser"
DB["Reset"]="Réinitialiser"
DB["Apply"]="Appliquer"
DB["Close"]="Fermer"
DB["Back"]="Retour"
DB["Next"]="Suivant"
DB["Previous"]="Précédent"
DB["Continue"]="Continuer"
DB["Cancel"]="Annuler"
DB["Accept"]="Accepter"
DB["Decline"]="Refuser"
DB["Confirm"]="Confirmer"
DB["Delete"]="Supprimer"
DB["Save"]="Enregistrer"
DB["Load"]="Charger"
DB["Enable"]="Activer"
DB["Disable"]="Désactiver"
DB["Enabled"]="Activé"
DB["Disabled"]="Désactivé"
DB["On"]="Activé"
DB["Off"]="Désactivé"
DB["None"]="Aucun"
DB["Unknown"]="Inconnu"
DB["N/A"]="N/A"
DB["Loading..."]="Chargement..."
DB["Please wait..."]="Veuillez patienter..."
DB["Are you sure?"]="Êtes-vous sûr ?"
DB["No results found"]="Aucun résultat"
DB["No items"]="Aucun objet"
DB["Empty"]="Vide"

DB["Reputation"]="Réputation"
DB["Experience"]="Expérience"
DB["Experience gained"]="Expérience gagnée"
DB["You receive loot:"]="Vous recevez le butin :"
DB["You receive item:"]="Vous recevez l'objet :"
DB["You create:"]="Vous créez :"
DB["Received"]="Reçu"
DB["Completed"]="Terminé"
DB["Failed"]="Échoué"
DB["In Progress"]="En cours"
DB["Ready"]="Prêt"
DB["Not ready"]="Pas prêt"

DB["Dungeon"]="Donjon"
DB["Raid"]="Raid"
DB["Battleground"]="Champ de bataille"
DB["Arena"]="Arène"
DB["World"]="Monde"
DB["Instance"]="Instance"
DB["Party"]="Groupe"
DB["Raid Group"]="Groupe de raid"
DB["Guild"]="Guilde"
DB["Friends"]="Amis"
DB["Ignore"]="Ignorer"

DB["Vendor"]="Marchand"
DB["Repair"]="Réparer"
DB["Repair All"]="Tout réparer"
DB["Buy"]="Acheter"
DB["Sell"]="Vendre"
DB["Buyback"]="Racheter"
DB["Cost"]="Coût"
DB["Price"]="Prix"

DB["Quest"]="Quête"
DB["Quests"]="Quêtes"
DB["Available Quests"]="Quêtes disponibles"
DB["Active Quests"]="Quêtes en cours"
DB["Turn In"]="Rendre"
DB["Abandon Quest"]="Abandonner la quête"
DB["Share Quest"]="Partager la quête"
DB["Quest Log"]="Journal de quêtes"
DB["Objectives"]="Objectifs"
DB["Rewards"]="Récompenses"
DB["Choose your reward:"]="Choisissez votre récompense :"
DB["You will receive:"]="Vous recevrez :"
DB["You may choose:"]="Vous pourrez choisir :"

DB["Spellbook"]="Livre de sorts"
DB["Talents"]="Talents"
DB["Glyphs"]="Glyphes"
DB["Achievements"]="Hauts faits"
DB["Collections"]="Collections"
DB["Mounts"]="Montures"
DB["Companions"]="Mascottes"
DB["Pets"]="Familiers"
DB["Bag"]="Sac"
DB["Bags"]="Sacs"
DB["Bank"]="Banque"
DB["Mailbox"]="Boîte aux lettres"
DB["Auction House"]="Hôtel des ventes"
DB["Flight Master"]="Maître de vol"
DB["Innkeeper"]="Aubergiste"
DB["Make this inn your home"]="Faites de cette auberge votre foyer"
DB["Binder"]="Lieur"
DB["Train me"]="Entraînez-moi"
DB["I would like to train."]="Je voudrais m'entraîner."
DB["I want to browse your goods."]="Je voudrais voir vos marchandises."
